// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQymGhXJKVU1z61FzuklBzJnwlwKguHw',
    appId: '1:766125777599:web:6719e3c0f5149c39a01c0a',
    messagingSenderId: '766125777599',
    projectId: 'financedashboardmobile',
    authDomain: 'financedashboardmobile.firebaseapp.com',
    storageBucket: 'financedashboardmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmDz3UzkH9SJjQacqcXdttpSaXL_L5qE',
    appId: '1:766125777599:android:d720e9b2190b1272a01c0a',
    messagingSenderId: '766125777599',
    projectId: 'financedashboardmobile',
    storageBucket: 'financedashboardmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxjh4hscAluZHRR9V5XZTsHQctF-O4ag',
    appId: '1:766125777599:ios:9975238f122299c3a01c0a',
    messagingSenderId: '766125777599',
    projectId: 'financedashboardmobile',
    storageBucket: 'financedashboardmobile.firebasestorage.app',
    iosBundleId: 'com.example.financedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxjh4hscAluZHRR9V5XZTsHQctF-O4ag',
    appId: '1:766125777599:ios:9975238f122299c3a01c0a',
    messagingSenderId: '766125777599',
    projectId: 'financedashboardmobile',
    storageBucket: 'financedashboardmobile.firebasestorage.app',
    iosBundleId: 'com.example.financedashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsQymGhXJKVU1z61FzuklBzJnwlwKguHw',
    appId: '1:766125777599:web:34980ff63afe7a6aa01c0a',
    messagingSenderId: '766125777599',
    projectId: 'financedashboardmobile',
    authDomain: 'financedashboardmobile.firebaseapp.com',
    storageBucket: 'financedashboardmobile.firebasestorage.app',
  );
}
